/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.Font;
import java.io.InputStream;

/**
 *
 * @author Felix Coral
 */
public class AttendanceRecord extends javax.swing.JPanel {

    /**
     * Creates new form AttendanceRecord
     */
    public AttendanceRecord() {
        initComponents();
         loadCustomFont();
    }
    private void loadCustomFont() {
        try {
            // Carga la fuente desde un archivo
            InputStream is = getClass().getResourceAsStream("/Fuentes/Arturo-Heavy_Outline_trial.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);

            // Deriva el tamaño de la fuente y aplica la fuente al JLabel
            jLabel6.setFont(font.deriveFont(Font.ITALIC , 20f));
            jLabel6.setFont(font.deriveFont(Font.ITALIC , 20f));
        } catch (Exception ex) {
            ex.printStackTrace();
            // Maneja cualquier excepción que pueda ocurrir al cargar la fuente
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Camara = new redondeado.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        camara = new redondeado.RoundedPanel();
        fecha = new redondeado.RoundedPanel();
        txt_nombre = new javax.swing.JLabel();
        codigo = new redondeado.RoundedPanel();
        txt_codigo = new javax.swing.JTextField();
        alumno = new redondeado.RoundedPanel();
        txt_dni = new javax.swing.JLabel();
        horaEntrada = new redondeado.RoundedPanel();
        txt_apellido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(215, 215, 215));
        setMaximumSize(new java.awt.Dimension(1045, 681));
        setMinimumSize(new java.awt.Dimension(1045, 681));
        setPreferredSize(new java.awt.Dimension(1045, 681));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Camara.setBackground(new java.awt.Color(152, 199, 202));
        Camara.setForeground(new java.awt.Color(0, 0, 0));
        Camara.setCornerRadius(8);
        Camara.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        Camara.setHoverColor(new java.awt.Color(62, 136, 147));
        Camara.setNormalColor(new java.awt.Color(152, 199, 202));
        Camara.setText("Camara");

        javax.swing.GroupLayout CamaraLayout = new javax.swing.GroupLayout(Camara);
        Camara.setLayout(CamaraLayout);
        CamaraLayout.setHorizontalGroup(
            CamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        CamaraLayout.setVerticalGroup(
            CamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        add(Camara, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 157, 48));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 60, 25));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 50, 25));

        jLabel4.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 60, 25));

        jLabel5.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DNI");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 60, 25));

        camara.setBackground(new java.awt.Color(255, 255, 255));
        camara.setForeground(new java.awt.Color(0, 0, 0));
        camara.setCornerRadius(8);
        camara.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        camara.setNormalColor(new java.awt.Color(255, 255, 255));
        camara.setText("");

        javax.swing.GroupLayout camaraLayout = new javax.swing.GroupLayout(camara);
        camara.setLayout(camaraLayout);
        camaraLayout.setHorizontalGroup(
            camaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        camaraLayout.setVerticalGroup(
            camaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        add(camara, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 310, 340));

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setCornerRadius(8);
        fecha.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        fecha.setNormalColor(new java.awt.Color(255, 255, 255));
        fecha.setText("");
        fecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        fecha.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 145, 36));

        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 157, 48));

        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setForeground(new java.awt.Color(0, 0, 0));
        codigo.setCornerRadius(8);
        codigo.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        codigo.setNormalColor(new java.awt.Color(255, 255, 255));
        codigo.setText("");
        codigo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_codigo.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo.setForeground(new java.awt.Color(0, 0, 0));
        txt_codigo.setBorder(null);
        codigo.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 145, 36));

        add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 157, 48));

        alumno.setBackground(new java.awt.Color(255, 255, 255));
        alumno.setForeground(new java.awt.Color(0, 0, 0));
        alumno.setCornerRadius(8);
        alumno.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        alumno.setNormalColor(new java.awt.Color(255, 255, 255));
        alumno.setText("");
        alumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_dni.setForeground(new java.awt.Color(0, 0, 0));
        alumno.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 145, 36));

        add(alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 157, 48));

        horaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        horaEntrada.setForeground(new java.awt.Color(0, 0, 0));
        horaEntrada.setCornerRadius(8);
        horaEntrada.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        horaEntrada.setNormalColor(new java.awt.Color(255, 255, 255));
        horaEntrada.setText("");
        horaEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_apellido.setForeground(new java.awt.Color(0, 0, 0));
        horaEntrada.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 145, 36));

        add(horaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 157, 48));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Buscar Alumnos");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public redondeado.RoundedPanel Camara;
    public redondeado.RoundedPanel alumno;
    public redondeado.RoundedPanel camara;
    public redondeado.RoundedPanel codigo;
    public redondeado.RoundedPanel fecha;
    public redondeado.RoundedPanel horaEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel txt_apellido;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JLabel txt_dni;
    public javax.swing.JLabel txt_nombre;
    // End of variables declaration//GEN-END:variables
}
