/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author Felix Coral
 */
public class Code extends javax.swing.JPanel {

    /**
     * Creates new form ChangePassword
     */
    public Code() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Continuar = new redondeado.RoundedPanel();
        NombreApellido = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 430));
        setMinimumSize(new java.awt.Dimension(400, 430));
        setPreferredSize(new java.awt.Dimension(400, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Para Restablecer Tu Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresa El Codigo Que Aacabar De Llegar  A Tu Correo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 20));

        Continuar.setBackground(new java.awt.Color(30, 133, 139));
        Continuar.setForeground(new java.awt.Color(255, 255, 255));
        Continuar.setCornerRadius(17);
        Continuar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        Continuar.setHoverColor(new java.awt.Color(152, 199, 202));
        Continuar.setName(""); // NOI18N
        Continuar.setNormalColor(new java.awt.Color(30, 133, 139));
        Continuar.setText("Continuar");
        Continuar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 40));

        NombreApellido.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        NombreApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(NombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 0, 190, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public redondeado.RoundedPanel Continuar;
    public javax.swing.JLabel NombreApellido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
