/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Felix Coral
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
       // asistenciaEfecto.setIcon(null);
        dasboardEfecto.setIcon(null);
        justificarEfecto.setIcon(null);
        cursosEfecto.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new redondeado.RoundedPanel();
        salir = new javax.swing.JLabel();
        cursos = new javax.swing.JLabel();
        justificar = new javax.swing.JLabel();
        dasboard = new javax.swing.JLabel();
        asistencia = new javax.swing.JLabel();
        asistenciaEfecto = new javax.swing.JLabel();
        dasboardEfecto = new javax.swing.JLabel();
        justificarEfecto = new javax.swing.JLabel();
        cursosEfecto = new javax.swing.JLabel();
        cambioPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(152, 199, 202));
        roundedPanel1.setCornerRadius(20);
        roundedPanel1.setHoverColor(new java.awt.Color(152, 199, 202));
        roundedPanel1.setNormalColor(new java.awt.Color(152, 199, 202));
        roundedPanel1.setText("");
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Salir - Efecto_Principal.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });
        roundedPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 659, -1, -1));

        cursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cursos - Principal.png"))); // NOI18N
        cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cursosMousePressed(evt);
            }
        });
        roundedPanel1.add(cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 505, -1, -1));

        justificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        justificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Justificar - Principal.png"))); // NOI18N
        justificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                justificarMousePressed(evt);
            }
        });
        roundedPanel1.add(justificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 392, -1, -1));

        dasboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Dashboard - Principal.png"))); // NOI18N
        dasboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dasboardMousePressed(evt);
            }
        });
        roundedPanel1.add(dasboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 279, -1, -1));

        asistencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Registro - Principal.png"))); // NOI18N
        asistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asistenciaMousePressed(evt);
            }
        });
        roundedPanel1.add(asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 171, -1, -1));

        asistenciaEfecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asistenciaEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Asistencia - Efecto_Principal.png"))); // NOI18N
        roundedPanel1.add(asistenciaEfecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 171, -1, -1));

        dasboardEfecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dasboardEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Dashboard - Efecto_Principal.png"))); // NOI18N
        roundedPanel1.add(dasboardEfecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 279, -1, -1));

        justificarEfecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        justificarEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Justificar - Efecto_Principal.png"))); // NOI18N
        roundedPanel1.add(justificarEfecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 392, -1, -1));

        cursosEfecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cursosEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cursos - Efecto_Principal.png"))); // NOI18N
        roundedPanel1.add(cursosEfecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 505, -1, -1));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 7, 63, 707));

        cambioPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cambioPrincipalLayout = new javax.swing.GroupLayout(cambioPrincipal);
        cambioPrincipal.setLayout(cambioPrincipalLayout);
        cambioPrincipalLayout.setHorizontalGroup(
            cambioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        cambioPrincipalLayout.setVerticalGroup(
            cambioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );

        jPanel1.add(cambioPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 20, 1045, 681));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        System.exit(0);
    }//GEN-LAST:event_salirMousePressed

    private void asistenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asistenciaMousePressed
        //Efecto
        asistenciaEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Asistencia - Efecto_Principal.png")));
        //Normal
        dasboardEfecto.setIcon(null);
        justificarEfecto.setIcon(null);
        cursosEfecto.setIcon(null);
    }//GEN-LAST:event_asistenciaMousePressed

    private void dasboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dasboardMousePressed
        //Efecto
        dasboardEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Dashboard - Efecto_Principal.png")));
        //Normal
        justificarEfecto.setIcon(null);
        cursosEfecto.setIcon(null);
        asistenciaEfecto.setIcon(null);
    }//GEN-LAST:event_dasboardMousePressed

    private void justificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_justificarMousePressed
        //Efecto
        justificarEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Justificar - Efecto_Principal.png")));
        //Normal
        cursosEfecto.setIcon(null);
        asistenciaEfecto.setIcon(null);
        dasboardEfecto.setIcon(null);
    }//GEN-LAST:event_justificarMousePressed

    private void cursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosMousePressed
        //Efecto
        cursosEfecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cursos - Efecto_Principal.png")));
        //Normal
        asistenciaEfecto.setIcon(null);
        dasboardEfecto.setIcon(null);
        justificarEfecto.setIcon(null);
    }//GEN-LAST:event_cursosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel asistencia;
    public javax.swing.JLabel asistenciaEfecto;
    public javax.swing.JPanel cambioPrincipal;
    public javax.swing.JLabel cursos;
    public javax.swing.JLabel cursosEfecto;
    public javax.swing.JLabel dasboard;
    public javax.swing.JLabel dasboardEfecto;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel justificar;
    public javax.swing.JLabel justificarEfecto;
    private redondeado.RoundedPanel roundedPanel1;
    public javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
