/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author Felix Coral
 */
public class SignIn extends javax.swing.JPanel {

    /**
     * Creates new form IniciarSesión
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Usuario = new texField.TextField();
        Ingresar = new redondeado.RoundedPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        RecuperarContraseña = new javax.swing.JLabel();
        Contraseña = new passwordField.PasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 430));
        setMinimumSize(new java.awt.Dimension(400, 430));
        setPreferredSize(new java.awt.Dimension(400, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Iniciar Sesión");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, -1));

        Usuario.setBackground(new java.awt.Color(255, 255, 255));
        Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Usuario.setText("u21221666");
        Usuario.setToolTipText("");
        Usuario.setCaretColor(new java.awt.Color(152, 199, 202));
        Usuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Usuario.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        Usuario.setLabelText("Ingrese Su Usuario");
        Usuario.setLineColor(new java.awt.Color(152, 199, 202));
        Usuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        Usuario.setSelectionColor(new java.awt.Color(30, 133, 139));
        add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 310, 50));

        Ingresar.setBackground(new java.awt.Color(30, 133, 139));
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setCornerRadius(17);
        Ingresar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        Ingresar.setHoverColor(new java.awt.Color(152, 199, 202));
        Ingresar.setName(""); // NOI18N
        Ingresar.setNormalColor(new java.awt.Color(30, 133, 139));
        Ingresar.setText("Ingresar");
        Ingresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 310, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sistema De Monitereo , Justificación y Asistencias");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 320, 240, -1));

        jSeparator2.setBackground(new java.awt.Color(152, 199, 202));
        jSeparator2.setForeground(new java.awt.Color(152, 199, 202));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 325, 40, 20));

        jSeparator1.setBackground(new java.awt.Color(152, 199, 202));
        jSeparator1.setForeground(new java.awt.Color(152, 199, 202));
        jSeparator1.setToolTipText("");
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSeparator1.setDoubleBuffered(true);
        jSeparator1.setRequestFocusEnabled(false);
        jSeparator1.setVerifyInputWhenFocusTarget(false);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 325, 50, 20));

        RecuperarContraseña.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        RecuperarContraseña.setForeground(new java.awt.Color(0, 0, 0));
        RecuperarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecuperarContraseña.setText("¿Olvidaste Tu Contraseña?");
        RecuperarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecuperarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecuperarContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecuperarContraseñaMouseExited(evt);
            }
        });
        add(RecuperarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 370, -1, -1));

        Contraseña.setBackground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("narcelith20");
        Contraseña.setLabelText("Ingresar Contraseña");
        add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RecuperarContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecuperarContraseñaMouseEntered
        RecuperarContraseña.setForeground(Color.RED);
    }//GEN-LAST:event_RecuperarContraseñaMouseEntered

    private void RecuperarContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecuperarContraseñaMouseExited
        RecuperarContraseña.setForeground(Color.BLACK);
    }//GEN-LAST:event_RecuperarContraseñaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public passwordField.PasswordField Contraseña;
    public redondeado.RoundedPanel Ingresar;
    public javax.swing.JLabel RecuperarContraseña;
    public texField.TextField Usuario;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
